spring:
  application:
    name: batch
  datasource:
    url: jdbc:postgresql://localhost:5432/db_batch
    username: postgres
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  batch:
    initialize-schema: ALWAYS
    job:
      enabled: false

server:
  port: 7979